---
title: blank
timezone: UTC
collections:
  news:
    title: News
    output: true
    permalink: "/news/:path/"
    defaults:
      layout: post
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
first_name: Prof. Dr. Nazan
middle_name: 
last_name: Yalcin Erik
email: nyalcin@gmail.com
description: 'Interested in both petroleum and coal geological processes. Extensive
  experience in source rock, organic geochemistry, trace element, and in-situ analytical
  techniques. Also proficient in basin modelling and organic geochemistry, including
  regional petroleum systems and prospect evaluations; source rock characterisation,
  quality and maturity; HC expulsion and migration focus; basinal heat controls; oil-oil
  and oil-source correlations through biomarkers. Competence in sedimentary provenance
  analysis using a number of techniques. Considerable experience in project management.
  Specialities: Geology; inorganic and organic geochemistry; Biomarkers, Source rocks,
  coal geochemistry, petroleum systems; basin modelling; coal petrography; stable
  isotopes.

'
Specialities: Geology; inorganic and organic geochemistry; Biomarkers, Source rocks,
  coal geochemistry, petroleum systems; basin modelling; coal petrography; stable
  isotopes.
footer_text: ''
icon: "\U0001F525"
url: 
baseurl: 
last_updated: true
impressum_path: 
navbar_fixed: true
footer_fixed: false
max_width: 800px
serve_og_meta: false
og_image: 
github_username: 
twitter_username: 
linkedin_username: nazan-yalçin-erik-799110186
scholar_userid: PQHEylgAAAAJ
orcid_id: 0000-0001-7849-8660
medium_username: 
quora_username: 
publons_id: 1438681
research_gate_profile: Nazan_Erik
blogger_url: 
work_url: 
keybase_username: 
wikidata_id: 
contact_note: ''
google_analytics: G-KNQ2QXV04T
panelbear_analytics: XXXXXXXXX
blog_name: blog
blog_description: 
permalink: "/blog/:year/:title/"
pagination:
  enabled: true
disqus_shortname: 
news_limit: 5
markdown: kramdown
highlighter: rouge
highlight_theme: github
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
include:
- _pages
exclude:
- bin
- Gemfile
- Gemfile.lock
- vendor
keep_files:
- CNAME
- ".nojekyll"
- ".git"
plugins:
- jekyll-email-protect
- jekyll-github-metadata
- jekyll-paginate-v2
- jekyll/scholar
- jekyll-twitter-plugin
- jemoji
scholar:
  last_name:
  - Yalcin Erik
  - Yalçın Erik
  first_name:
  - Nazan
  - N.
  style: apa
  locale: en
  source: "/_bibliography/"
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: "@*"
enable_google_analytics: true
enable_panelbear_analytics: false
enable_mansory: true
enable_math: true
enable_tooltips: false
enable_darkmode: false
show_social_icons: false
academicons:
  version: 1.9.0
  integrity: sha512-W4yqoT1+8NLkinBLBZko+dFB2ZbHsYLDdr50VElllRcNt2Q4/GSs6u71UHKxB7S6JEMCp5Ve4xjh3eGQl/HRvg==
bootstrap:
  version: 4.5.2
  integrity:
    css: sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg==
    js: sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ==
fontawesome:
  version: 5.14.0
  integrity: sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==
jquery:
  version: 3.5.1
  integrity: sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==
mathjax:
  version: 3.1.2
mansory:
  version: 4.2.2
  integrity: sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI=
mdb:
  version: 4.19.1
  integrity:
    css: sha512-RO38pBRxYH3SoOprtPTD86JFOclM51/XTIdEPh5j8sj4tp8jmQIx26twG52UaLi//hQldfrh7e51WzP9wuP32Q==
    js: sha512-Mug9KHKmroQFMLm93zGrjhibM2z2Obg9l6qFG2qKjXEXkMp/VDkI4uju9m4QKPjWSwQ6O2qzZEnJDEeCw0Blcw==
popper:
  version: 2.4.4
  integrity: sha512-eUQ9hGdLjBjY3F41CScH3UX+4JDSI9zXeroz7hJ+RteoCaY+GP/LDoM8AO+Pt+DRFw3nXqsjh9Zsts8hnYv8/A==
